apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_USERNAME: andreas
  DOCKER_INFLUXDB_INIT_PASSWORD: asakel64
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: c1ab53eb2ed756f2b508c5cc8a116bcca62a64195fcadcb30780dd222ed2f4ff
  DOCKER_INFLUXDB_INIT_ORG: mnl
  DOCKER_INFLUXDB_INIT_BUCKET: mqtt_to_influx
  DOCKER_INFLUXDB_INIT_RETENTION: 4d
  DOCKER_INFLUXDB_INIT_PORT: "8086"
  DOCKER_INFLUXDB_INIT_HOST: influxdb