apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
      server {
          listen 80;
          server_name localhost;

          location / {
              # reverse proxy for uvicorn
              proxy_pass http://api-control-robot-service:8000;
              proxy_connect_timeout 1200s;
              proxy_send_timeout 1200s;
              proxy_read_timeout 1200s;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_redirect off;
              proxy_buffering off;
          }
      }
